export const initialProfile = {
  name: "Sahadat Hossen",
  roles: [
    "Full Stack MERN Developer",
    "React Specialist",
    "Node.js Engineer",
    "MongoDB Architect",
    "API Designer",
  ],
  bioBlurb:
    "I build scalable, performant web applications from database to deployment. Passionate about clean code, great UX, and the MERN stack.",
  statusText: "Available for new opportunities",
  statusAvailable: true,
  avatarUrl: "/profile.jpg",
  cvUrl: "/resume.pdf",
  floatingBadges: [
    { label: "MongoDB", color: "from-green-500 to-emerald-600", delay: "0s", top: "15%", left: "8%" },
    { label: "Express", color: "from-gray-500 to-gray-700", delay: "1.5s", top: "70%", left: "5%" },
    { label: "React", color: "from-cyan-400 to-blue-500", delay: "0.8s", top: "20%", right: "8%" },
    { label: "Node.js", color: "from-green-400 to-lime-600", delay: "2s", top: "65%", right: "6%" },
    { label: "TypeScript", color: "from-blue-500 to-blue-700", delay: "1.2s", top: "45%", left: "3%" },
    { label: "Next.js", color: "from-slate-600 to-slate-800", delay: "2.5s", top: "40%", right: "4%" },
  ],
  aboutTitle: "Crafting digital experiences",
  aboutP1:
    "I'm a full-stack developer with 1+ years of experience building modern web applications. My core stack centers on MongoDB, Express, React, and Node.js (MERN), supplemented with TypeScript and Next.js.",
  aboutP2:
    "Beyond code, I specialize in web analytics, conversion tracking (GA4, GTM, Meta Pixel), and technical SEO. I love building things that look stunning, perform flawlessly, and deliver measurable business value.",
  currentlyBuilding: "SaaS Dashboard App",
  stats: [
    { iconName: "Briefcase", value: "1+", label: "Years of Experience" },
    { iconName: "Star", value: "10+", label: "Projects Delivered" },
    { iconName: "Coffee", value: "1k+", label: "Cups of Coffee" },
    { iconName: "MapPin", value: "Remote", label: "Work Style" },
  ],
  highlights: [
    { emoji: "⚡", text: "Building real-time apps with Node.js & WebSocket" },
    { emoji: "🌐", text: "RESTful API design and development" },
    { emoji: "🚀", text: "CI/CD pipelines with GitHub Actions & Docker" },
    { emoji: "🎨", text: "Pixel-perfect UIs with React & Next.js" },
  ],
  email: "sahadat.hossen1435@gmail.com",
  phone: "+8801606081657",
  whatsappNumber: "8801606081657",
  whatsappMessage: "Hi Sahadat, I visited your portfolio and would like to connect!",
  messengerUrl: "https://m.me/sahadat.hossen.1435",
  location: "Dhaka, Bangladesh",
  socials: [
    {
      platform: "github",
      label: "GitHub",
      value: "github.com/Sahadat-Hossen1",
      href: "https://github.com/Sahadat-Hossen1",
    },
    {
      platform: "linkedin",
      label: "LinkedIn",
      value: "linkedin.com/in/sahadathossen",
      href: "https://linkedin.com/in/sahadathossen",
    },
    {
      platform: "whatsapp",
      label: "Whatsapp",
      value: "+8801606081657",
      href: "https://wa.me/8801606081657",
    },
    {
      platform: "email",
      label: "Email",
      value: "sahadat.hossen1435@gmail.com",
      href: "mailto:sahadat.hossen1435@gmail.com",
    },
    {
      platform: "twitter",
      label: "Twitter",
      value: "twitter.com",
      href: "https://twitter.com",
    },
  ],
  sections: {
    hero: true,
    about: true,
    skills: true,
    projects: true,
    experience: true,
    contact: true,
    floatingChat: true,
  },
};

export const initialSkills = [
  { name: "React", icon: "⚛️", level: 95, color: "#38bdf8", category: "Web Development", order: 1 },
  { name: "Next.js", icon: "▲", level: 90, color: "#e2e8f0", category: "Web Development", order: 2 },
  { name: "JavaScript", icon: "🟡", level: 97, color: "#eab308", category: "Web Development", order: 3 },
  { name: "TypeScript", icon: "🔷", level: 88, color: "#3b82f6", category: "Web Development", order: 4 },
  { name: "Node.js", icon: "🟢", level: 93, color: "#84cc16", category: "Web Development", order: 5 },
  { name: "Express.js", icon: "⚡", level: 90, color: "#94a3b8", category: "Web Development", order: 6 },
  { name: "MongoDB", icon: "🍃", level: 92, color: "#10b981", category: "Web Development", order: 7 },
  { name: "Tailwind CSS", icon: "🎨", level: 92, color: "#06b6d4", category: "Web Development", order: 8 },
  { name: "Redux", icon: "🔮", level: 82, color: "#7c3aed", category: "Web Development", order: 9 },
  { name: "REST APIs", icon: "🔗", level: 95, color: "#f59e0b", category: "Web Development", order: 10 },
  { name: "Git & GitHub", icon: "🐙", level: 95, color: "#a78bfa", category: "Web Development", order: 11 },
  { name: "Vercel & Netlify", icon: "▲", level: 90, color: "#00c7b7", category: "Web Development", order: 12 },

  { name: "Google Tag Manager", icon: "🏷️", level: 95, color: "#4285f4", category: "Analytics & Tracking", order: 13 },
  { name: "Google Analytics 4", icon: "📊", level: 92, color: "#ea4335", category: "Analytics & Tracking", order: 14 },
  { name: "Meta Pixel & CAPI", icon: "♾️", level: 90, color: "#0081fb", category: "Analytics & Tracking", order: 15 },
  { name: "Google Ads Tracking", icon: "🎯", level: 88, color: "#fbbc04", category: "Analytics & Tracking", order: 16 },
  { name: "LinkedIn Insight Tag", icon: "💼", level: 85, color: "#0a66c2", category: "Analytics & Tracking", order: 17 },
  { name: "TikTok Pixel Tracking", icon: "🎵", level: 85, color: "#fe2c55", category: "Analytics & Tracking", order: 18 },
];

export const initialSkillTags = [
  "DataLayer Architecture",
  "Server-Side Tracking",
  "E-commerce Purchase Tracking",
  "Enhanced Conversions",
  "Custom Event Triggers",
  "Consent Mode (v2)",
  "Mongoose",
  "JWT",
  "Postman",
  "Vite",
  "Figma",
  "ESLint",
];

export const initialProjects = [
  {
    title: "ShopFlow E-Commerce & Full Tracking",
    description: "MERN Stack E-Commerce with GTM, GA4 & Meta Pixel",
    longDesc:
      "A complete full-stack e-commerce platform built with Next.js, Node.js, and MongoDB. Integrated with DataLayer, Google Analytics 4 (GA4) E-commerce tracking, and Meta Pixel Conversion API via Google Tag Manager.",
    image: "/assets/images/projects/project-1.jpg",
    tags: ["Next.js", "Node.js", "MongoDB", "GTM", "GA4", "Meta Pixel", "Tailwind CSS"],
    github: "https://github.com",
    live: "https://example.com",
    emoji: "🛒",
    featured: true,
    stars: 48,
    order: 1,
  },
  {
    title: "DevMetrics & Event Visualizer",
    description: "Full-Stack Web App with Real-Time Event Tracking",
    longDesc:
      "A developer productivity and event metrics portal with interactive dashboards, custom event triggers, TikTok & LinkedIn Tag integration, and automated user journey tracking.",
    image: "/assets/images/projects/project-2.jpg",
    tags: ["React", "Express.js", "Tailwind CSS", "DataLayer", "GA4", "TikTok Pixel"],
    github: "https://github.com",
    live: "https://example.com",
    emoji: "📊",
    featured: true,
    stars: 35,
    order: 2,
  },
  {
    title: "CollabFlow Task Manager",
    description: "Collaborative project board with real-time UI",
    longDesc:
      "Full-stack project management app with interactive boards, responsive UI, and custom analytics event tracking on task completion.",
    image: "/assets/images/projects/project-3.jpg",
    tags: ["React", "Node.js", "MongoDB", "Tailwind CSS"],
    github: "https://github.com",
    live: "https://example.com",
    emoji: "🚀",
    featured: false,
    stars: 24,
    order: 3,
  },
  {
    title: "AuthKit & User Management",
    description: "JWT Authentication & Custom Event Logging",
    longDesc:
      "Secure authentication system supporting JWT, OAuth, and conversion tracking for user signups and login flows.",
    image: "/assets/images/projects/project-4.jpg",
    tags: ["Node.js", "Express", "JWT", "GTM"],
    github: "https://github.com",
    live: "https://example.com",
    emoji: "🔐",
    featured: false,
    stars: 19,
    order: 4,
  },
  {
    title: "Food Discovery & Recipe App",
    description: "Interactive Recipe Finder with Filter Tracking",
    longDesc:
      "A responsive React application featuring real-time search, category filtering, and button click event tracking.",
    image: "/assets/images/projects/project-5.jpg",
    tags: ["React", "REST API", "Tailwind CSS", "Meta Pixel"],
    github: "https://github.com",
    live: "https://example.com",
    emoji: "🍲",
    featured: false,
    stars: 15,
    order: 5,
  },
  {
    title: "Live Weather & Utility App",
    description: "Location-based real-time weather application",
    longDesc:
      "Weather app fetching live meteorological data with interactive UI widgets and search analytics tracking.",
    image: "/assets/images/projects/project-6.jpg",
    tags: ["JavaScript", "OpenWeather API", "CSS3", "GA4"],
    github: "https://github.com",
    live: "https://example.com",
    emoji: "🌤️",
    featured: false,
    stars: 12,
    order: 6,
  },
];

export const initialExperiences = [
  {
    role: "Full-Stack Developer & Analytics Specialist",
    company: "Inspire Soft",
    companyUrl: "https://example.com",
    location: "Dhaka, Bangladesh",
    period: "May 2026 – Present (4 Months)",
    type: "Full-time",
    current: true,
    bullets: [
      "Developing responsive, modern web applications using React, Next.js, and Node.js with clean UI and API integrations.",
      "Implementing end-to-end web tracking via Google Tag Manager (GTM), setting up GA4 custom events and DataLayer architecture.",
      "Configuring Meta Pixel and standard/custom conversion tracking to ensure accurate data capture.",
      "Collaborating with team members to optimize code performance, fix UI bugs, and streamline client project workflows.",
    ],
    tags: ["React", "Next.js", "Node.js", "MongoDB", "GTM", "GA4", "Meta Pixel"],
    order: 1,
  },
  {
    role: "Freelance Web Developer & Tracking Expert",
    company: "Self-Employed (Freelance)",
    companyUrl: "https://example.com",
    location: "Remote",
    period: "2025 – Present",
    type: "Freelance",
    current: false,
    bullets: [
      "Successfully delivered 5+ full-stack and front-end web development projects with tailored client requirements.",
      "Configured precise tracking setups using GTM, GA4, Meta Pixel, TikTok Pixel, and LinkedIn Insight Tags.",
      "Built custom e-commerce and business websites with interactive UI, secure backends, and full event tracking capabilities.",
      "Ensured high performance, responsive layouts, and cross-browser compatibility across all client deliverables.",
    ],
    tags: ["MERN Stack", "Tailwind CSS", "GTM", "GA4", "Meta Pixel", "TikTok Pixel", "LinkedIn Tag"],
    order: 2,
  },
];
